**参考莫烦Python的简要教程**

# **Numpy的属性**


**ndim：维度**

**shape：行数和列数**

**size：元素个数** 

In [1]:
import numpy as np

In [207]:
array = np.array([[1,2,3],[2,3,4]]) 

print(array.shape) #行数和列数
print(array.size) #元素个数
print(array.ndim) #维数

(2, 3)
6
2


# **array：创建数组**

## **关键字**

**array：创建数组**

**dtype：指定数据类型**

**zeros：创建数据全为0**

**ones：创建数据全为1**

**empty：创建数据接近0**

**arrange：按指定范围创建数据**

**linspace：创建线段**

In [13]:
a = np.array([2, 23, 4])
print(a)
#没有逗号分隔

[ 2 23  4]


**dtype int float**

In [17]:
a = np.array([2, 23, 4], dtype = np.int64)
print(a.dtype)

int64


In [18]:
a = np.array([2, 23, 4], dtype = np.int)
print(a.dtype)

int32


In [19]:
a = np.array([2, 23, 4], dtype = np.int32)
print(a.dtype)

int32


In [21]:
a = np.array([2, 23, 4], dtype = np.float)
print(a.dtype)

float64


In [23]:
a = np.array([2, 23, 4], dtype = np.float32)
print(a.dtype)

float32


**指定行列数**

In [24]:
array = np.array([[1, 2, 3],
                 [5, 6, 7]])
print(array)

[[1 2 3]
 [5 6 7]]


**全0**

In [26]:
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**全1**

In [28]:
a = np.ones((5, 8), dtype = np.int16)
print(a)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [49]:
xArry = np.ones((3, 4))
xArry

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**全空**

In [30]:
a = np.empty((5, 6))
print(a)

[[ 1.26711112e-311  9.63428009e-322  0.00000000e+000  0.00000000e+000
   0.00000000e+000  5.02034658e+175]
 [ 2.52545406e-052  2.58143117e-057  3.27422224e+179  5.44227784e-062
   1.47763641e+248  1.16096346e-028]
 [ 7.69165785e+218  1.35617292e+248  4.18160512e+175  3.77104371e-061
   5.16185112e-066  8.98380644e-067]
 [ 4.25850093e-096  6.32299154e+233  3.65588282e+233  1.74569531e+238
   1.11763132e+261  1.16318408e-028]
 [ 2.24729310e+174  1.56605686e-076  1.65612288e-076  6.36886359e-062
   1.03030371e-071 -2.20141488e-227]]


**arange**

In [50]:
a = np.arange(10, 101, 7)
print(a)
#类似于Python中的arange 7为步长

[10 17 24 31 38 45 52 59 66 73 80 87 94]


**reshape**

In [43]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**linspace**

In [47]:
a = np.linspace(1, 100, 20)
print(a)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [48]:
a = np.linspace(1, 100, 20).reshape(10, 2)
print(a)

[[  1.           6.21052632]
 [ 11.42105263  16.63157895]
 [ 21.84210526  27.05263158]
 [ 32.26315789  37.47368421]
 [ 42.68421053  47.89473684]
 [ 53.10526316  58.31578947]
 [ 63.52631579  68.73684211]
 [ 73.94736842  79.15789474]
 [ 84.36842105  89.57894737]
 [ 94.78947368 100.        ]]


# **Numpy基础运算**

**+ - * / 幂次 sin... < ==等**

In [66]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print('a:', a)
print('b:', b)
print('a,b:', a, b)
c = a + b
d = a - b
e = a * b #逐个相乘 必须结构一样
f = b / a
g = a**2
h = b**3
print('a+b:',c)
print('a-b:',d)
print('a*b:',e)
print('b/a:',f)
print('a^2:', g)
print('b^3:', h)

c = 10*np.sin(a)
print('10*sin(a):', c)
#cos tan...

print('b:', b)
print(b<3)

print('b:', b)
print(b==3)

a: [10 20 30 40]
b: [0 1 2 3]
a,b: [10 20 30 40] [0 1 2 3]
a+b: [10 21 32 43]
a-b: [10 19 28 37]
a*b: [  0  20  60 120]
b/a: [0.         0.05       0.06666667 0.075     ]
a^2: [ 100  400  900 1600]
b^3: [ 0  1  8 27]
10*sin(a): [-5.44021111  9.12945251 -9.88031624  7.4511316 ]
b: [0 1 2 3]
[ True  True  True False]
b: [0 1 2 3]
[False False False  True]


**矩阵相乘**

In [82]:
a = np.array([[9, 1, 8],
              [2, 1, 0]])
b = np.arange(12).reshape((3, 4))
print('a:')
print(a)
print('b:')
print(b) 

c_dot = np.dot(a, b) 
c_dot_2 = a.dot(b)    #另一种表示
print('a和b的矩阵相乘:')
print(c_dot)
print(c_dot_2)

a:
[[9 1 8]
 [2 1 0]]
b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a和b的矩阵相乘:
[[ 68  86 104 122]
 [  4   7  10  13]]
[[ 68  86 104 122]
 [  4   7  10  13]]


**求和 求最小值 求最大值**

In [96]:
a = np.random.random((2, 4))
print(a)
#随机生成0到1的数字

print(np.sum(a))
print(np.min(a))
print(np.max(a))
      

[[0.68395722 0.32871112 0.08393997 0.40696852]
 [0.11737653 0.39442263 0.41932678 0.86160738]]
3.2963101445303495
0.08393997269296327
0.8616073839681309


**在行数、列数中求和**

In [108]:
print(np.sum(a, axis=1))    #在列数求和
print(np.sum(a, axis=0))    #在行数种求和
print(np.min(a, axis=1))
print(np.min(a, axis=0))
print(np.max(a, axis=1))
print(np.max(a, axis=0))

[1.50357683 1.79273331]
[0.80133375 0.72313375 0.50326675 1.2685759 ]
[0.08393997 0.11737653]
[0.11737653 0.32871112 0.08393997 0.40696852]
[0.68395722 0.86160738]
[0.68395722 0.39442263 0.41932678 0.86160738]


**argmin() argmax(),求矩阵中最小元素和最大元素的索引**

In [113]:
A = np.arange(2, 14).reshape((3, 4))
print(A)
print(np.argmin(A))
print(np.argmax(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


**求均值、中位数**

In [149]:
print(np.mean(A))
print(np.average(A)) #两种表达方式

print(np.median(A)) #求中位数

8.5
8.5
8.5


**累加的效果**

In [145]:
print(A)
print(np.cumsum(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[ 14  27  39  50  60  69  77  84  90  95  99 102]


**差的效果**

In [128]:
print(A)
print(np.diff(A)) #后一个减前一个数的差

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**找出非0的数**

In [130]:
print(np.nonzero(A))

#结果解释：第0行第0列，第0行第1列

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


**逐行排序**

In [133]:
A = np.arange(14, 2, -1).reshape(3, 4)
print(A)

print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


**矩阵转置**

In [139]:
A = np.arange(14, 2, -1).reshape(3, 4)
print(A)

print(np.transpose(A))
print(A.T)    #另一种表示

print((A.T).dot(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


**clip函数**

In [143]:
#clip(Array,Array_min,Array_max)
#让大于max的数变为max,让小于min的数变为min

print(A)
print(np.clip(A, 3, 8))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[8 8 8 8]
 [8 8 8 7]
 [6 5 4 3]]


**补充一下按列按行**

In [152]:
print(A)
print(np.median(A, axis = 0)) #按行计算
print(np.median(A, axis = 1)) #按列计算

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[10.  9.  8.  7.]
[12.5  8.5  4.5]


# **Numpy索引**

**一维索引**

In [255]:
A = np.arange(3, 15)
print(A)
print(A[3])

A = np.arange(3, 15).reshape(3, 4)
print(A)
print(A[2])    #行数
 

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]


**二维索引**

In [256]:
print(A[1][1])
print(A[1, 1])

print(A[1, :])
print(A[:, 1])
print(A[:, :])

print(A[1, 1:2])  #第一行 第1~2这个数
print(A[1, 1:3])

for row in A:
    print(row)    #按行迭代

for column in A.T:
    print(column)     #实现按列迭代的效果

print(A.flatten())    
    
for item in A.flat:
    print(item)

8
8
[ 7  8  9 10]
[ 4  8 12]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[8]
[8 9]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


## **Numpy array 合并**

**vstack 上下合并**

**hstack 左右合并**

In [269]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])


c = np.vstack((A, B))
print(c)
print(A.shape)
print(c.shape)
print(c)

c = np.hstack((A, B))
print(c.shape)
print(c)

[[1 1 1]
 [2 2 2]]
(3,)
(2, 3)
[[1 1 1]
 [2 2 2]]
(6,)
[1 1 1 2 2 2]


In [270]:
print('A:')
print(A)
print('B:')
print(B)

print('A.T:')
print(A.T)    #翻转不过来

print('newA1:')
print(A[np.newaxis,:])    #行上加一个维度 

print('newA2:')    
print(A[:,np.newaxis])    #纵向加维度 

print('添加新维度后：')
A = np.array([1, 1, 1])[:,np.newaxis]
B = np.array([2, 2, 2])[:,np.newaxis]
c = np.hstack((A, B))
print('A:')
print(A)
print('B:')
print(B)
print(A.shape, c.shape)
print(c)

A:
[1 1 1]
B:
[2 2 2]
A.T:
[1 1 1]
newA1:
[[1 1 1]]
newA2:
[[1]
 [1]
 [1]]
添加新维度后：
A:
[[1]
 [1]
 [1]]
B:
[[2]
 [2]
 [2]]
(3, 1) (3, 2)
[[1 2]
 [1 2]
 [1 2]]


**再探newaxis**

In [265]:
HH = np.arange(2, 8).reshape(2, 3)
print(HH)
print(HH.shape)

JJ = HH[np.newaxis,:]
print(JJ)
print(JJ.shape)

KK = HH[:,np.newaxis]
print(KK)
print(KK.shape)

[[2 3 4]
 [5 6 7]]
(2, 3)
[[[2 3 4]
  [5 6 7]]]
(1, 2, 3)
[[[2 3 4]]

 [[5 6 7]]]
(2, 1, 3)


插曲：验证属性输出

In [208]:
MM = np.array([1, 2, 3, 4, 5, 6])
print(np.shape(MM))

(6,)


**concatenate**

In [268]:
print('A:')
print(A)
print('B:')
print(B)

print('C:')
C = np.concatenate((A,B,B,A),axis=0)    #上下这个方向合并
print(C)

print('C:')
C = np.concatenate((A,B,B,A),axis=1)    #左右这个方向合并
print(C)

A:
[[1]
 [1]
 [1]]
B:
[[2]
 [2]
 [2]]
C:
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
C:
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


## **Numpy array 分割**

In [272]:
A = np.arange(12).reshape(3, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**split**

In [280]:
print(np.split(A, 2, axis = 1))
print(np.split(A, 3, axis = 0))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


**array_split**

In [282]:
print(np.array_split(A, 3, axis = 1))    #不等项分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


**vsplit**

**hsplit**

In [284]:
print(np.vsplit(A, 3))
print(np.hsplit(A, 2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# **Numpy copy & deep copy**

**关于赋值, = 的赋值方式会带有关联性**

In [291]:
a = np.arange(4)
print(a)

b = a
c = a
d = b

a[0] = 23
print(a)
print(b)
print(d)

b is a

[0 1 2 3]
[23  1  2  3]
[23  1  2  3]
[23  1  2  3]


True

In [292]:
c is a

True

In [293]:
d is a

True

In [294]:
d[1:3] = [55, 66]

print(a)

[23 55 66  3]


**copy() 的赋值方式没有关联性 **

In [298]:
mm = a.copy()

print(a)
print(mm)

a[3] = 100
print(a)
print(mm)

mm is a

[ 23  55  66 100]
[ 23  55  66 100]
[ 23  55  66 100]
[ 23  55  66 100]


False