**Python_for_Data_Analysis学习**

# **ndrarray 一种多维数组**

**Numpy优于Python内置的list,例子：**

**建议不要写from numpy import *（尽管这能避免你后面每次写‘np.’）因为numpy和Python内置的函数有重名**

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 29.9 ms


In [3]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Wall time: 904 ms


**对ndrarray进行运算就像对标量运算一样**

In [4]:
import numpy as np
data = np.random.randn(4, 5)                    
data


array([[-0.76668079,  0.29854794, -1.91471536,  1.0577287 ,  0.68157533],
       [ 0.35267526, -0.76334415,  1.63043797,  0.5263242 , -0.51768206],
       [ 0.03045042, -0.15327658,  0.54558645,  2.39795876, -0.04119612],
       [-0.81047   , -0.72745988,  1.95996783, -0.50848662,  0.49992951]])

In [5]:
data * 10

array([[ -7.66680787,   2.9854794 , -19.14715358,  10.57728696,
          6.81575327],
       [  3.52675257,  -7.63344152,  16.30437971,   5.26324195,
         -5.17682059],
       [  0.30450418,  -1.53276582,   5.4558645 ,  23.9795876 ,
         -0.41196123],
       [ -8.10470002,  -7.27459877,  19.59967834,  -5.08486615,
          4.99929512]])

In [6]:
data + data

array([[-1.53336157,  0.59709588, -3.82943072,  2.11545739,  1.36315065],
       [ 0.70535051, -1.5266883 ,  3.26087594,  1.05264839, -1.03536412],
       [ 0.06090084, -0.30655316,  1.0911729 ,  4.79591752, -0.08239225],
       [-1.62094   , -1.45491975,  3.91993567, -1.01697323,  0.99985902]])

**说明维数**

In [7]:
data.shape

(4, 5)

**说明数据类型**

In [8]:
data.dtype 

dtype('float64')

# **创建ndrray**

## **array()：将输入数据转化为ndarray**

In [9]:
data1 = [1, 3.2, 4, 0, 9]
arr1 = np.array(data1) #array函数：创建数组
arr1

array([1. , 3.2, 4. , 0. , 9. ])

In [10]:
data2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(data2) #等长的list会被创建成多维数组
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr2.ndim #输出维度 嵌套了几层 就是几

2

In [12]:
data2_ = [[1, 2, 3, 0], [4, 5, 6]]
arr2_ = np.array(data2_) #不等长的list则不会被创建成多维数组
arr2_

array([list([1, 2, 3, 0]), list([4, 5, 6])], dtype=object)

**asarray():将输入数据转化为ndarray 如果本身为ndarray则不转换**

In [13]:
np.asarray(arr2)

array([[1, 2, 3],
       [4, 5, 6]])

## **zeros empty**

**zeros and ones create arrays of 0s or 1s, respectively, with a
given length or shape**

In [14]:
np.zeros(10) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**empty creates an array without initializing its values to any par‐
ticular value**

In [17]:
np.empty((2, 3, 2))

array([[[8.81912238e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.14332416e+160]],

       [[1.53540811e-075, 5.19556684e+170],
        [2.87882540e+180, 5.49275168e+170],
        [2.33826100e-052, 9.33795422e+164]]])

**ones_like：以另一个数组为参数，根据其形状创建一个全1数组**

**one_like以及empty_like类似**

In [18]:
np.ones_like(data)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## **arange()——Python内置函数range的数组版**

In [19]:
List1 = list(range(10))
List1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
L = np.arange(10)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **eye、identity**

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**不太重要**

两个函数的原型为：

np.identity(n, dtype=None)

np.eye(N, M=None, k=0, dtype=<type ‘float’>)；

np.identity只能创建方形矩阵 

np.eye可以创建矩形矩阵，且k值可以调节，为1的对角线的位置偏离度，0居中，1向上偏离1，2偏离2，以此类推，-1向下偏离。值绝对值过大就偏离出去了，整个矩阵就全是0了。

--------------------- 
作者：Gobsd 
来源：CSDN 
原文：https://blog.csdn.net/Gobsd/article/details/56485791 
版权声明：本文为博主原创文章，转载请附上博文链接！

# **ndarray的数据类型**

In [23]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype 

dtype('float64')

**转换数据类型**

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [25]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

**float变int 发生截断**

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.4, 11.8])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.4, 11.8])

In [27]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 11])

**string变数字**

**小心用**

In [28]:
numeric_strings = np.array(['1.3', '2.7', '-42'], dtype = np.string_)
numeric_strings

array([b'1.3', b'2.7', b'-42'], dtype='|S3')

In [29]:
numeric_strings.astype(np.float) #np.float也可以写成float

array([  1.3,   2.7, -42. ])

**数组的dtype的另一种用法**

In [30]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .367, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
empty_unit32 = np.empty(8, dtype='u4')
empty_unit32

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

**注意：astype会创建一个新的数组**


# **数组与标量之间的计算**

**大小相等的数组之间的算术运算——对每个元素进行运算**

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

数组并不是矩阵，例子：

In [34]:
arr1 = np.array([[3, 5, 7], [22, 28, 62]])
arr2 = np.array([[32, 51, 11, 22], [72, 42, 28, 62], [20, 23, 123, 544]])
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (2,3) (3,4) 

**数组与标量的算术运算——对每个元素进行运算**

In [39]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

**相同大小数组之间的比较**

In [41]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [42]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# **基本的索引和切片**